name: "[Coin] - Testing with 'Nitrogen' - Manual"
run-name: Test with ðŸ¤– Nitrogen by @${{github.actor}} ${{inputs.families &&  format('families={0}',inputs.families) || ''}} ${{inputs.currencies && format('currencies={0}',inputs.currencies) || ''}}
on:
  workflow_dispatch:
    inputs:
      families:
        description: coin families to test, separated with commas (,)
        required: false
      currencies:
        description: currency ids to test, separated with commas (,)
        required: false
      features:
        description: features to test(send,sendMax,tokens,staking)
        required: false
      speculos_websocket:
        description: check to use speculos with Websocket
        type: boolean
        required: false
        default: false

jobs:
  run-bot:
    uses: ./.github/workflows/bot-reusable.yml
    with:
      seed_index: "7"
      concurrency_group: bot-seed7
      bot_environment: testing
      runs_on: ledger-live-4xlarge
      slack_icon_emoji: ":bot-seed7:"
      bot_filter_families: ${{ inputs.families }}
      bot_filter_currencies: ${{ inputs.currencies }}
      bot_filter_features: ${{ inputs.features }}
      speculos_websocket: ${{ inputs.speculos_websocket }}
