name: Build and Test
on:
  push:
    branches:
      - main
      - develop
      - release
      - hotfix
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'develop' && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  determine-affected:
    name: "Turbo Affected"
    uses: LedgerHQ/ledger-live/.github/workflows/turbo-affected-reusable.yml@feat/ci-improvements
    with:
      head_branch: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
      base_branch: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}

  # LLD
  build-desktop:
    name: "Build Desktop"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-desktop') && github.event.pull_request.head.repo.full_name == github.repository }}
    uses: LedgerHQ/ledger-live/.github/workflows/build-desktop-reusable.yml@feat/ci-improvements
    secrets: inherit

  test-desktop:
    name: "Test Desktop"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-desktop') && github.event.pull_request.head.repo.full_name == github.repository}}
    uses: LedgerHQ/ledger-live/.github/workflows/test-desktop-reusable.yml@feat/ci-improvements
    secrets: inherit

  # LLM
  build-mobile:
    name: "Build Mobile"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-mobile') && github.event.pull_request.head.repo.full_name == github.repository}}
    uses: LedgerHQ/ledger-live/.github/workflows/build-mobile-reusable.yml@feat/ci-improvements
    secrets: inherit

  test-mobile:
    name: "Test Mobile"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-mobile') && github.event.pull_request.head.repo.full_name == github.repository}}
    uses: LedgerHQ/ledger-live/.github/workflows/test-mobile-reusable.yml@feat/ci-improvements
    secrets: inherit

  test-mobile-e2e:
    name: "Test Mobile E2E"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-mobile') && github.event.pull_request.head.repo.full_name == github.repository}}
    uses: LedgerHQ/ledger-live/.github/workflows/test-mobile-e2e-reusable.yml@feat/ci-improvements
    secrets: inherit

  # Tests
  test-libraries:
    name: "Test Libraries"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'libs') && github.event.pull_request.head.repo.full_name == github.repository}}
    uses: LedgerHQ/ledger-live/.github/workflows/test-libs-reusable.yml@feat/ci-improvements
    secrets: inherit

  test-design-system:
    name: "Test Design System"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'libs/ui') && github.event.pull_request.head.repo.full_name == github.repository}}
    uses: LedgerHQ/ledger-live/.github/workflows/test-design-system-reusable.yml@feat/ci-improvements
    secrets: inherit

  # Final Check required
  ok:
    name: "OK"
    needs:
      - build-desktop
      - test-desktop
      - build-mobile
      - test-mobile
      - test-mobile-e2e
      - test-libraries
      - test-design-system
    runs-on: ubuntu-22.04
    if: always() && !cancelled()
    steps:
      - name: Check result
        if: contains(needs.*.result, 'failure')
        run: exit 1
