name: yolo
on:
  pull_request:

jobs:
  the-matrix:
    outputs:
      linux: ${{ steps.output-ubuntu-latest.outcome }}
      macos: ${{ steps.output-macos-latest.outcome }}
      windows: ${{ steps.output-windows-latest.outcome }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: output
        id: output-${{ matrix.os }}
        run: |
          echo "zeubie"

  reports:
    needs: [the-matrix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("${{ needs.the-matrix.outputs }}");
